### ISSUE TITLE
Correct ot-ctl command in README

### ISSUE THREAD

**Issue by MonicaisHer** [canonical/chip-tool-snap#25]
The following command should be updated to use 'openthread-border-router.ot-ctl,' and it would be helpful to also include a link to the OTBR snap or wiki:
https://github.com/canonical/chip-tool-snap/blob/33cc5bfa860015b17f3e908ef703b722e52fd01e/README.md?plain=1#L59C8-L59C14

**Comment by farshidtz** [comment]
The command is correct. The ot-ctl used there isn't exposed from the [OpenThread Border Router snap](https://snapcraft.io/openthread-border-router).

I have nevertheless created a PR to add some explanation and links: #43
