### ISSUE TITLE
Standard output of the Chip Tool command not in test artifacts

### ISSUE THREAD

**Issue by farshidtz** [canonical/chip-tool-snap#33]
Looking at the latest run [here](https://github.com/canonical/chip-tool-snap/actions/runs/7539854155?pr=31), I noticed that the chip-tool logs produced as artifacts only include the journal logs. The standard output of the Chip Tool command isn't collected.

_Originally posted by @farshidtz in https://github.com/canonical/chip-tool-snap/issues/31#issuecomment-1893456630_

**Comment by farshidtz** [comment]
> Where is the best place to output the chip tool command's stdout? Directly in the [chip-tool test suite](https://github.com/canonical/chip-tool-snap/blob/main/tests/snap_test.go#L79-L84) when calling utils.Exec(), or as part of the [utils .exec()](https://github.com/canonical/matter-snap-testing/blob/main/utils/exec.go#L29)?

The issue isn't about printing the logs. The utils.exec function executes the command and returns the logs. It already supports printing of the log stream.

**Comment by MonicaisHer** [comment]
There are two places where the stdout log can be exported—either on the chip-tool test side or on the matter-snap-testing side (similar to [SnapDumpLogs](https://github.com/canonical/matter-snap-testing/blob/main/utils/snap.go#L127)). It could probably be placed on the matter-snap-testing side for reusability. However, the current Matter snaps (OTBR snap and GPIO snap) already have all the logs from journalctl using SnapDumpLogs.
