### ISSUE TITLE
Thread test device hardcoded to ttyACM0

### ISSUE THREAD

**Issue by jpm-canonical** [canonical/chip-tool-snap#62]
On my laptop the fingerprint reader is also a ttyACM device. If I reboot without the nRF dongle plugged in, the fingerprint reader is mounted as ttyACM0. The nRF dongle will then be mounted as ttyACM1.

The thread test does not allow configuring which ttyACM should be used.

Just like we can specify the infra address, we should also be able to specify the tty device.
Around here: https://github.com/canonical/chip-tool-snap/blob/a3550bd103a4ad516bfeb40ada8f7d2983b54892/tests/thread_tests/local.go#L44

**Comment by farshidtz** [comment]
Fixed by #66
