### ISSUE TITLE
Do not run tests with sudo

### ISSUE THREAD

**Issue by jpm-canonical** [canonical/chip-tool-snap#63]
If #55 gets merged, we can (and likely should) update the tests to run without using sudo.

Note: The upgrade test installs chip-tool from the stable track in the store. The stable version still requires sudo. Therefore the upgrade test should keep on using sudo until stable is updated to the version of chip-tool that does not require sudo.

**Comment by farshidtz** [comment]
Could it be automated by checking the revision number?
https://pkg.go.dev/github.com/canonical/matter-snap-testing@v1.0.0-beta.3/utils#SnapRevision
