### ISSUE TITLE
Separate installation of node and ZAP into a standalone part

### ISSUE THREAD

**Issue by MonicaisHer** [canonical/chip-tool-snap#7]
The following script could be moved to a new part called `nodjs-zap`:
https://github.com/canonical/chip-tool-snap/blob/d1d4c940dd1050dca6af2b840834e8702b43d184/snap/snapcraft.yaml#L39-L67

**Comment by farshidtz** [comment]
To be done as part of the open PR: https://github.com/canonical/chip-tool-snap/pull/6
